name: Challenge 1
on:
  push:
    branches: main
jobs:
  Job1:
    runs-on:  ubuntu-latest
    steps:
      - name:  display-date-ubuntu
        run:  date
  Job2:
    runs-on:  windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run:  ls .github/workflows
  Job3:
    runs-on:  macos-latest
    steps:
      - name: display-date-mac
        run:  date
  Job4:
    needs:  [Job1, Job2, Job3]
    runs-on:  windows-latest
    steps:
      - name: display-date
        run:  get-date -f "D"  